name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [ push ]
jobs:
  container-job:
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres_db:
        # Docker Hub image
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          # will assign a random free host port
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
#      keycloak:
#        image: bitnami/keycloak:latest
#        volumes:
#          - realm-export.json:/tmp/realm-export.json
#        env:
#          KEYCLOAK_USER: user
#          KEYCLOAK_PASSWORD: bitnami
#          KC_DB: postgres
#          KC_DB_USERNAME: postgres
#          KC_DB_PASSWORD: postgres
#          KC_DB_URL: jdbc:postgresql://localhost:5432/postgres
#          JAVA_OPTS_APPEND: "-Dkeycloak.profile.feature.upload_scripts=enabled"
#          KEYCLOAK_IMPORT: /tmp/realm-export.json
#        ports:
#          - 8080:8080
#      keycloak:
#        image: quay.io/keycloak/keycloak:20.0.1
#        ports:
#          - "8080:8080"
#        environment:
#          KEYCLOAK_ADMIN: admin
#          KEYCLOAK_ADMIN_PASSWORD: admin
#          KC_DB: postgres
#          KC_DB_USERNAME: postgres
#          KC_DB_PASSWORD: postgres
#          KC_DB_URL: jdbc:postgresql://localhost:5432/postgres
#        command:
#          - start-dev
#          - --import-realm
#        volumes:
#          - ./docker/auth/realm.json:/opt/keycloak/data/import/realm.json
    steps:
      - uses: actions/checkout@v3
#      - name: Check conn 1
#        run: ls
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
      - name: Check conn 2
        run: |
          wget https://github.com/keycloak/keycloak/releases/download/19.0.1/keycloak-19.0.1.tar.gz
          tar -xvzf keycloak-19.0.1.tar.gz
          export KC_DB_URL_HOST=jdbc:postgresql://localhost:5432/postgres
          rm ./keycloak-19.0.1/conf/keycloak.conf
          cp ./keycloak.conf ./keycloak-19.0.1/conf
          mkdir -p ./keycloak-19.0.1/data/import
          cp ./realm-export.json ./keycloak-19.0.1/data/import
          ./keycloak-19.0.1/bin/kc.sh start-dev --db-url-host=jdbc:postgresql://localhost:5432/postgres --import-realm & mvn --batch-mode --update-snapshots verify